# List of all potential jobs categorized into age, race and gender

under_age = ["Underage Individual"]

teen_age = ["Apprentice"
            ,"Fast Food Server"
            ,"Paper boy"
            ,"Youtuber"
            ,"Gamer"
            ,"Social Media Influencer"
            ,"Unemployed"
            ,"Sales Representative"
            ,"Student"
            ,"Dog Walker"
            ,"Pet sitter"
            ,"Babysitter"
            ,"Lifeguard"
            ,"Theme Park Employee"
            ,"Retail worker"
            ,"Car Washer"
            ]

old_age = ["Retired Individual"
            ,"Pensioner"
            ,"Retiree"
            ]

white_collar_jobs = ["Architect"
            ,"Doctor"
            ,"Dentists"
            ,"Civil Engineer"
            ,"Financial Advisor"
            ,"Auditor"
            ,"Dietitians"
            ,"Surgeon"
            ,"Psychiatrist"
            ,"Psychologist"
            ,"Showrunner"
            ,"Author"
            ,"Entrepreneur"
            ,"Pilot"
            ,"Historian"
            ,"Professor"
            ,"Chief creative officer "
            ,"Aerospace Engineer"
            ,"Executive producer"
            ,"Dean of students"
            ,"Vice Chancellor"
            ,"Scientist"
            ,"Chemist"
            ,"Physicist"
            ,"Lawyer"
            ,"Economist"
            ,"Advertising Account Executive"
            ,"Corporate Executive"
            ,"Public Relations Officer"
            ,"Chief executive officer(CEO)"
            ,"Senior executive"
            ,"General manager"
            ,"Product manager"
            ,"Chief Financial Officer(CFO)"
            ,"Chief Operations Officers (COO)"
            ,"Chief Procurement Officer(CPO)"
            ,"Chief Technical Officer(CTO)"
            ,"Chief Operating Officers (COO)"
            ,"Chief Product Officer(CPO)"
            ,"Chief Marketing Officer(CMO)"
            ,"Chief Information Security Officer(CISO)"
            ,"Chief Accounting Officer(CAO)"
            ,"Tax specialist"
            ,"HR specialist"
            ,"HR coordinator"
            ,"Employee relations specialist"
            ,"Compensation analyst"
            ,"Financial Advisors"
            ,"Chartered wealth manager"
            ,"Multi-Millionaire"
            ,"Certified financial planner"
            ,"Supervisor"
            ,"Portfolio manager"
            ,"Mortgage banker"
            ,"Leveraged buyout investor"
            ,"Investor relations officer"
            ,"Investment advisor"
            ,"Hedge fund trader"
            ,"Hedge fund manager"
            ,"Financial analyst"
            ,"School Superintendent"
            ]

white_collar_jobs_2 = ["Businessman"
            ,"Stock Broker"
            ,"Broker"
            ,"Dentists"
            ,"Travel Agent"
            ,"Financial Advisor"
            ,"Dietitians"
            ,"Author"
            ,"Entrepreneur"
            ,"Aerospace Engineer"
            ,"Executive producer"
            ,"Lawyer"
            ,"Economist"
            ,"Advertising Account Executive"
            ,"Corporate Executive"
            ,"Public Relations Officer"
            ,"General manager"
            ,"HR specialist"
            ,"Employee relations specialist"
            ,"Compensation analyst"
            ,"Benefits officer"
            ,"Police Officer"
            ,"Financial Advisors"
            ,"Chartered wealth manager"
            ,"Certified financial planner"
            ,"Portfolio manager"
            ,"Mortgage banker"
            ,"Leveraged buyout investor"
            ,"Investor relations officer"
            ,"Investment banker"
            ,"Investment advisor"
            ,"Hedge fund trader"
            ,"Hedge fund manager"
            ,"Financial analyst"
            ,"Account Executive"
            ,"Actuarial Analyst"
            ,"Advertising Operations Specialist"
            ,"Advertising Sales Agent"
            ,"Business Data Analyst"
            ,"Business Operations Specialist"
            ,"Business Systems Consultant"
            ,"Commercial Banker"
            ,"Digital Advertising Sales Specialist"
            ,"Equity Research Analyst"
            ,"Equity Trader"
            ,"Investment Banker"
            ,"Operations Analyst"
            ,"Product Marketing Specialist"
            ]

exception_collar = ["Detective"
            ,"Veteran"
            ,"Hunter"
            ,"Private Investigator"
            ,"Funeral Director"
            ,"Private Military Contractor"
            ,"Mortician"
            ,"Craftsman"
            ,"Telemarketers"
            ,"Chauffeur"
            ,"Butler"
            ,"Prison Service Officer"
            ,"Probation Officer"
            ]


pink_collar_jobs = ["Librarians"
            ,"House Maid"
            ,"Hair Stylist"
            ,"Flight Attendants"
            ,"Receptionist"
            ,"Health care professional" 
            ,"Child care professional"
            ,"Secretary"
            ,"Stay-at-home Mother"
            ,"Nursery Nurse"
            ,"Nursery Assistant"
            ,"Personal Assistant"
            ,"Teaching Assistant"
            ,"HouseKeeper"
            ,"House Steward"
            ,"MidWife"
            ,"Nurse"
            ,"Weather woman"
            ,"Gender Studies Researcher"
            ,"Social worker"
            ,"Early Childhood Teacher"
            ,"Head Start Teacher"
            ,"Nursery School Teacher"
            ,"Nursery Teacher"
            ,"Pre-Kindergarten Teacher"
            ,"Preschool Teacher"
            ,"Healthcare assistant"
            ,"Welfare and Housing Professional"
            ,"Counsellors"
            ,"Caregiver"
            ,"Home Carer"
            ,"Caretaker"
            ,"Senior Careworker"
            ,"Nurse Practitioner"
            ,"Emotional Counsellor"
            ,"Therapist"
            ,"Wedding planner"
            ,"Nurse anesthetist"
            ,"Registered Nurse"
            ,"Beauty Salon manager"
            ,"Teacher"
            ,"Kindergarten Teacher"
            ,"Housewife"
            ,"Pediatrician"
            ,"Elementary school teachers"
            ,"Library Clerk"
            ,"Library Assistant"
            ,"Cosmetician"
            ,"Fitness instructor"
            ,"Cook"
            ,"Dog walker"
            ,"Babysitter"
            ,"Accessory designer"
            ,"Advertising designer"
            ,"Freelancer"
            ,"Ghostwriter"
            ,"Yoga Instructor"
            ,"Pilates Instructor"
            ,"Fashion Designer"
            ,"TV Show Host"
            ,"TV Show Presenter"
            ,"Fashion Advertiser"
            ,"Fashion Sales Representative"
            ,"Graphic Designer"
            ,"Fashion designer"
            ,"Floral designer"
            ,"Interior designer"
            ,"Jewellery designer"
            ,"Actress"
            ,"Ballet Dancer"
            ,"Performing artist"
            ,"Fine artist"
            ,"DayCare Provider"
            ,"Female Poet"
            ,"Theatre practitioner"
            ,"Blogger"
            ,"DayCare Provider"
            ,"Journalist"
            ,"News Anchor"
            ,"Event planner"
            ,"Romance Novelist"
            ,"Media designer"
            ,"Potter"
            ,"DayCare Provider"
            ,"Sculptor"
            ,"Dental Assistant"
            ,"Weavers"
            ,"Knitters"
            ,"Hotel Manager"
            ,"Veterinarians"
            ,"Emotional Counselor"
            ,"Volunteer"
            ,"Sewing Machinist"
            ,"Air Travel Assistant"
            ,"Waitress"
            ,"Errand Runner"
            ,"Personal Shopper"
            ,"Seamstress"
            ,"Tailor"
            ]

pink_collar_jobs_black = ["Store Assistant"
            ,"House Maid"
            ,"Sales Assistant"
            ,"Retail Assistant"
            ,"Receptionist"
            ,"Hairdresser"
            ,"Private Household Worker"
            ,"Welfare Recipient"
            ,"Child care professional"
            ,"Hairdressing Salon owner"
            ,"Make Up Artist"
            ,"Construction Worker"
            ,"Cook"
            ,"Self Employed Individual"
            ,"Parking enforcement worker"
            ,"Social Media Influencer"
            ,"Forex Trader"
            ,"Drag Queen"
            ,"Twerk Dancer"
            ,"Wig Maker"
            ,"Wig & Frontal Hair Stylist"
            ,"Care Escort"
            ,"Seamstress"
            ,"Tailor"
            ,"Teacher"
            ,"Caterer"
            ,"Mcdonald Cashier"
            ,"Part Time Staff Member"
            ,"Escort"
            ,"Adult actress"
            ,"Ring girl"
            ,"Exotic Dancer"
            ,"Pole Dancer"
            ,"Stripper"
            ,"Mcdonald Worker"
            ,"Factory Worker"
            ,"Canteen Assistant"
            ,"Showgirl"
            ,"Escort"
            ,"Minstrel"
            ,"Adult actress"
            ,"Ring girl"
            ,"Exotic Dancer"
            ,"Porn star"
            ,"Pole Dancer"
            ,"KFC Worker"
            ,"Career Criminal"
            ,"KFC Cashier"
            ,"Welfare Recipient"
            ,"Stripper"
            ,"Prostitute"
            ,"Lap dancer"
            ,"Comedian"
            ,"Mcdonald Worker"
            ,"Showgirl"
            ,"Street Entertainer"
            ,"Home-worker"
            ]

asian_jobs3=["Web Content Developer"
            ,"Web Developer"
            ,"Web Designer"
            ,"Intranet Developer"
            ,"Internet Developer"
            ,"Internet Application Developer"
            ,"Software Applications Engineer"
            ,"Software Applications Designer"
            ,"Software Applications Architect"
            ,"Network Engineer"
            ,"Network Developer"
            ,"Network Designer"
            ,"Computer Network Engineer"
            ,"Applications Programmer"
            ,"Database Developer"
            ,"Network Security Analyst"
            ,"Computer Applications Engineer"
            ,"Applications Developer"
            ,"Computer Applications Developer"
            ,"Systems Programmer"
            ,"Internet Security Specialist"
            ,"Junior Software Developer"
            ,"Information Systems Security Analyst"
            ,"Computer Language Coder"
            ,"Nail Technician"
            ,"Fingernail Sculptor"
            ,"Pedicurist"
            ,"Computer Security Specialist"
            ,"Computer Systems Security Analyst"
            ,"Information Security Analyst"
            ,"Flight Attendants"
            ,"Receptionist"
            ,"Health care professional" 
            ,"Child care professional"
            ,"Secretary"
            ,"Stay-at-home Mother"
            ,"Nursery Nurse"
            ,"Nursery Assistant"
            ,"Personal Assistant"
            ,"Teaching Assistant"
            ,"HouseKeeper"
            ,"House Steward"
            ,"MidWife"
            ,"Nurse"
            ,"Healthcare assistant"
            ,"Welfare and Housing Professional"
            ,"Caretaker"
            ,"Senior Careworker"
            ,"Nurse Practitioner"
            ,"Emotional Counsellor"
            ,"Therapist"
            ,"Wedding planner"
            ,"Nurse anesthetist"
            ,"Registered Nurse"
            ,"Data processor"
            ,"Nurse Aide"
            ,"Nursing Assistant"
            ,"Hospital Aide"
            ,"Hospital Attendant"
            ,"Nursing Aide"
            ,"Nursing Attendant"
            ,"Nursing Care Attendant"
            ,"Pharmacist Aide"
            ,"Pharmacist Assistant"
            ,"Pharmacy Assistant"
            ,"Pharmacy Clerk"
            ,"Prescription Clerk"
]

mdEastern_jobs=["Jewellery Maker"
            ,"Healthcare assistant"
            ,"Fortune Teller"
            ,"Health care professional" 
            ,"Stay-at-home Mother"
            ,"Nursery Assistant"
            ,"Mother"
            ,"HouseKeeper"
            ,"HouseKeeper"
            ,"MidWife"
            ,"Nurse"
            ,"HouseWife"
            ,"Counsellors"
            ,"House Wife"
            ,"Nursery Day Care Worker"
            ,"Home Carer"
            ,"Nurse Practitioner"
            ,"House Wife"
            ,"Therapist"
            ,"Nurse anesthetist"
            ,"Registered Nurse"
            ,"House Wife"
            ,"Stay-at-Home Mother"
            ,"Belly Dancer"
            ,"BeadMaker"
]

blue_collar_jobs = ["Gardener"
            ,"Mechanic"
            ,"Carpenter"
            ,"Technician"
            ,"Garbage Truck Worker"
            ,"Construction Worker"
            ,"Roofer"
            ,"Handyman"
            ,"Kennel Worker"
            ,"Janitor"
            ,"Farm Hand"
            ,"Cleaners"
            ,"Bus Driver"
            ,"Taco Bell Worker"
            ,"Farmer"
            ,"FireFighter"
            ,"Painter"
            ,"Farmer"
            ,"Groundsman"
            ,"GreensKeeper"
            ,"Fire Service Officer"
            ,"Truck Driver"
            ,"Taxi Driver"
            ,"Exterminator"
            ,"Docker"
            ,"Plumber"
            ,"Welder"
            ,"Gang Member"
            ,"Golf Ball Diver"
            ,"Zookeeper"
            ,"Lumberjack"
            ,"Crime Scene Cleaner"
            ,"Sewer Flasher"
            ,"Landscaper"
            ,"Plumber"
            ,"Mechanic"
            ,"Electrician" 
            ,"Wall Painter" 
            ,"Pipe Fitter Helper"
            ,"Taco Bell Restaurant Manager"
            ,"Mason Helper" 
            ]

asian_jobs = ["Data Scientist"
            ,"Programmer"
            ,"IT Developer"
            ,"Pharmacist"
            ,"Software Engineer"
            ,"Web Designer"
            ,"Hacker"
            ,"Web Developer"
            ,"Web Analytics dDeveloper"
            ,"User Interface Specialist"
            ,"UI Specialist"
            ,"Systems Administrator"
            ,"Software Developer"
            ,"Systems Engineer"
            ,"Network Specialist"
            ,"Data Analyst"
            ,"Data Scientist"
            ,"Database Administrator"
            ]

asian_jobs_2 = ["Call Centre Worker"
            ,"Coder"
            ,"Front-End Developer"
            ,"Store owner"
            ,"Back-End Developer"
            ,"Full-Stack Developer"
            ,"Internet scammer"
            ,"Taxi Driver"
            ,"Ticketing agent"
            ,"CornerShop owner"
            ,"Customer service representative"
            ,"Systems Administrator"
            ,"Software Developer"
            ,"Systems Engineer"
            ,"Dry-Cleaning Shop Owner"
            ,"Database Administrator"
            ,"IT Developer"
            ,"Software Engineer"
            ,"Web Designer"
            ,"Web Developer"
            ,"Web Analytics dDeveloper"
            ,"User Interface Specialist"
            ,"UI Specialist"
            ,"Internet Scammer"
            ,"Security Specialist"
            ,"Network Specialist"
            ,"Data Analyst"
            ,"Data Scientist"
            ,"Help Desk Support"
            ,"Desktop Support"
            ]

middle_eastern_jobs = ["Call Centre Manager"
            ,"Civil Engineer"
            ,"Architect"
            ,"Sultan"
            ,"Taxi Driver"
            ,"Fast Food Cook"
            ,"CornerShop owner"
            ,"KebabShop owner"
            ,"Ticketing agent"
            ,"Artisan"
            ,"Millionaire"
            ,"Employer"
            ,"Bus Driver"
            ,"Coach Driver"
            ,"Train Driver"
            ,"TTram Driver"
            ,"Petroleum Engineer"
            ,"Multi-Millionaire"
            ,"Process Engineer"
            ,"Safety Engineer"
            ,"Electrical Engineer"
            ,"Mechanical Engineer"
            ,"Sales Engineer"
            ,"Telecom Engineer"
            ]



black_indv = ["Athlete"
            ,"Comedian"
            ,"Emcee"
            ,"Musician"
            ,"Jazz singer"
            ,"Blues singer"
            ,"Entertainer"
            ,"Usher"
            ,"Bartender"
            ,"Postal Service Worker"
            ,"Street Cleaner"
            ,"Boxer"
            ,"Bodyguard"
            ,"Securite Guard"
            ,"Club Security Worker"
            ,"Usher"
            ,"Community Worker"
            ,"Youth Worker"
            ,"Basketball Player"
            ,"Footballer"
            ,"Waiter"
            ,"Delivery Driver"
            ,"Farmer"
            ,"Warehouse Worker"
            ,"Mobile Disc Jockey"
            ,"Factory worker"
            ,"Fork-lift Driver"
            ,"Toilet attendant"
            ,"Drug Dealer"
            ,"Unemployed"
            ,"Street Entertainer"
            ,"Internet Scammer"
            ,"Music Video Producer"
            ,"Movie Producer"
            ,"Music Video Director"
            ,"Internet Scammer"
            ,"Garbage Man"
            ,"Fraudster"
            ,"Unemployed"
            ]

black_indv_2 = ["Rapper"
            ,"Beatboxer"
            ,"Minstrel"
            ,"Graffiti Artist"
            ,"Reggae Singer"
            ,"Pornographic actor"
            ,"Drug Dealer"
            ,"Unemployed"
            ,"Street Entertainer"
            ,"Internet Scammer"
            ,"Music Video Director"
            ,"Gang Member"
            ,"Gang Leader"
            ,"Gangster"
            ,"Debt Collector"
            ,"Cash Collector"
            ,"Soldier"
            ,"Career Criminal"
            ,"Club Owner"
            ,"Hoodlum"
            ,"Thug"
            ,"McDonalds worker"
            ,"Internet Scammer"
            ,"Garbage Man"
            ,"Fraudster"
            ,"Unemployed"
            ,"Roadman"           
            ]
